### ISSUE TITLE
这不是一个issue

### ISSUE THREAD

**Issue by QwertyJack** [CatGG-101/11mh#1]
欧阳兄你好！

我是大学在校生，会点编程，打dota，上11mh，看到你的自动签到脚本，很像认识一下你。

这是[我的](https://github.com/QwertyJack/yavis/tree/master/11mh.net)

**Comment by QwertyJack** [comment]
github上没找到你的联系方式，所以就给你issue了。XD

**Comment by CatGG-101** [comment]
哈哈哈， 你好， 很高兴认识你， 我快毕业了 @QwertyJack

**Comment by QwertyJack** [comment]
q或微信啥的？

**Comment by CatGG-101** [comment]
test
